import type { ComponentDef, Theme, Token, TokenValueMap } from '@/types';
import { USE_CASES } from '@/lib/useCases';
import { MUI_MAPPING } from '@/lib/muiTheme';

// Phase C export — generates a self-contained Markdown reference for a theme.
// Decisions as text: committable, diffable, the seed of a Brand Constitution.

const isDecisionToken = (k: string) =>
  k.startsWith('semantic.') || k.startsWith('radius.') || k.startsWith('spacing.') || k.startsWith('font.');

export function generateThemeMarkdown(
  theme: Theme,
  components: ComponentDef[],
  tokens: Token[],
  resolved: TokenValueMap,
): string {
  const tokenMap: Record<string, Token> = {};
  tokens.forEach((t) => { tokenMap[t.key] = t; });

  const lines: string[] = [];
  lines.push(`# ${theme.name} — Design System`);
  lines.push('');
  lines.push(`_Generated by Design System Manager. Renders on real MUI components._`);
  lines.push('');

  // ---- Tokens (decisions) ----
  lines.push('## Tokens');
  lines.push('');
  const groups: [string, (k: string) => boolean][] = [
    ['Color', (k) => k.startsWith('semantic.color.')],
    ['Radius', (k) => k.startsWith('semantic.radius.') || k.startsWith('radius.')],
    ['Spacing', (k) => k.startsWith('semantic.spacing.') || k.startsWith('spacing.')],
    ['Typography', (k) => k.startsWith('semantic.font.') || k.startsWith('font.')],
    ['Elevation', (k) => k.startsWith('semantic.shadow.') || k.startsWith('shadow.')],
  ];
  for (const [label, match] of groups) {
    const keys = tokens.map((t) => t.key).filter((k) => isDecisionToken(k) && match(k));
    if (!keys.length) continue;
    lines.push(`### ${label}`);
    lines.push('');
    lines.push('| Token | Intent | Value |');
    lines.push('| --- | --- | --- |');
    for (const k of keys) {
      const intent = tokenMap[k]?.description || '';
      const value = resolved[k] ?? tokenMap[k]?.value ?? '';
      lines.push(`| \`${k}\` | ${intent} | \`${value}\` |`);
    }
    lines.push('');
  }

  // ---- Components ----
  lines.push('## Components');
  lines.push('');
  const byCat: Record<string, ComponentDef[]> = {};
  components.forEach((c) => { (byCat[c.category || 'Uncategorized'] ||= []).push(c); });

  for (const [cat, list] of Object.entries(byCat)) {
    lines.push(`### ${cat}`);
    lines.push('');
    for (const c of list) {
      lines.push(`#### ${c.name}`);
      lines.push('');
      lines.push(`- **ID:** \`${c.id}\``);
      lines.push(`- **Renders as:** ${MUI_MAPPING[c.id] || 'MUI component'}`);
      lines.push('');

      if (c.tokensUsed.length) {
        lines.push('**Token decisions**');
        lines.push('');
        lines.push('| Token | Intent | Value |');
        lines.push('| --- | --- | --- |');
        for (const k of c.tokensUsed) {
          const intent = tokenMap[k]?.description || '';
          const value = resolved[k] ?? tokenMap[k]?.value ?? '';
          lines.push(`| \`${k}\` | ${intent} | \`${value}\` |`);
        }
        lines.push('');
      }

      if (c.variants?.length) {
        lines.push('**Variants:** ' + c.variants.map((v) => `${v.name}${v.description ? ` (${v.description})` : ''}`).join('; '));
        lines.push('');
      }

      const usage = USE_CASES[c.id];
      if (usage) {
        lines.push('**Usage**');
        lines.push('');
        for (const uc of usage.cases) lines.push(`- _${uc.title}_ — ${uc.description}`);
        lines.push('');
        lines.push('**Do**');
        for (const d of usage.guidance.do) lines.push(`- ${d}`);
        lines.push('');
        lines.push("**Don't**");
        for (const d of usage.guidance.dont) lines.push(`- ${d}`);
        lines.push('');
      }

      if (c.a11y?.description) {
        lines.push(`**Accessibility:** ${c.a11y.description}`);
        lines.push('');
      }
    }
  }

  return lines.join('\n');
}
